In [2]:
import torch
import numpy as np
from sklearn.preprocessing import StandardScaler




import xlrd
import pandas as pd
book = xlrd.open_workbook('prepareddata.xlsx')
sheet = book.sheet_by_name('Sheet1')
data = [[sheet.cell_value(r, c)
         for c in range(0,8)] for r in range(0,7272)]

scaler = StandardScaler()


standardised_data = scaler.fit_transform(data)
print(scaler.mean_, scaler.var_)

np.random.shuffle(standardised_data)
array1 = standardised_data[:, 0:5]
array2 = standardised_data[:, 5:8]
x = torch.tensor(array1)
y = torch.tensor(array2)

print(x)
print(y)


[1.17685992e+00 2.50797002e+03 2.03207622e+00 3.30000000e+02
 3.00000000e-01 1.50880269e-02 4.55572536e+01 2.53751017e-02] [5.29632128e-01 1.01472949e+07 1.74973000e+00 2.70000000e+04
 4.00000000e-02 3.34068516e-05 4.87490021e+03 2.03739307e-04]
tensor([[ 0.5045,  0.8613,  0.1405, -1.0954,  1.0000],
        [ 0.1467,  0.0117,  0.2623,  0.9129,  1.0000],
        [-1.5107, -0.5442, -1.5362, -0.1826,  1.0000],
        ...,
        [ 1.1630,  1.8615,  0.8470, -0.1826,  1.0000],
        [-0.6056, -0.6405, -0.6497, -1.0954, -1.0000],
        [-0.3502, -0.5747, -0.3860, -1.0954, -1.0000]], dtype=torch.float64)
tensor([[-0.4081,  1.9218, -0.2342],
        [ 0.3233, -0.9203,  0.8399],
        [-0.5712, -0.9917,  0.1352],
        ...,
        [-0.5653,  0.8689, -0.9051],
        [-0.1466, -0.4099,  0.4206],
        [-0.7863, -0.3249, -0.3923]], dtype=torch.float64)


In [3]:
import torch.nn as nn
class Net(nn.Module):
    def __init__(self, D_in, H1, H2, D_out):
 
        super(Net, self).__init__()
        self.linear1 = nn.Linear(D_in, H1) 
        self.linear2 = nn.Linear(H1, H2)
        self.linear3 = nn.Linear(H2, D_out)
  
    def forward(self, x):
    
        x = torch.sigmoid(self.linear1(x))
        x = torch.sigmoid(self.linear2(x))
        x = self.linear3(x)
        return x



In [4]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H1, H2, D_out = 50, 5, 20, 12, 3
model = Net(D_in, H1, H2, D_out)
loss_fn = torch.nn.MSELoss(reduction='mean')

In [5]:
from tqdm import tqdm
model.train()
learning_rate = 5e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

epochs = 20

for epoch in range (epochs+1):
    
        for i in tqdm(range(0, len(x), N)):
            batch_x = x[i:i+N]
            batch_y = y[i:i+N]
    # Forward pass
            optimizer.zero_grad()
            dx_dt_pred = model(batch_x.float())
   
    # Compute and print loss.
            loss = loss_fn(dx_dt_pred, batch_y.float())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
       
            loss.backward()
            optimizer.step()
        print(epoch, loss.item())



print(batch_y)    
print(dx_dt_pred)


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 527.70it/s]


0 0.9540542960166931


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 939.36it/s]


1 0.8732340931892395


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 931.33it/s]


2 0.7415192127227783


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 912.44it/s]


3 0.6169151067733765


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 979.27it/s]


4 0.5280095934867859


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 955.90it/s]


5 0.4608737528324127


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 926.52it/s]


6 0.40873804688453674


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 988.95it/s]


7 0.371812641620636


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 993.06it/s]


8 0.3496018946170807


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 953.28it/s]


9 0.3378002345561981


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 886.06it/s]


10 0.3312988579273224


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 940.45it/s]


11 0.3267859220504761


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 926.54it/s]


12 0.32285207509994507


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 839.61it/s]


13 0.3190932869911194


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 930.63it/s]


14 0.315446674823761


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 965.17it/s]


15 0.31192389130592346


100%|██████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 1009.59it/s]


16 0.30853861570358276


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 975.23it/s]


17 0.30529436469078064


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 913.42it/s]


18 0.30218586325645447


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 922.69it/s]


19 0.2992022931575775


100%|███████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 975.94it/s]


20 0.2963295876979828
tensor([[-6.8202e-01,  1.1990e+00, -6.9044e-02],
        [ 1.0044e+00, -4.1148e-01,  9.2802e-01],
        [-8.1858e-01,  1.1723e+00, -3.4972e-01],
        [-2.6167e-03, -7.5117e-01, -6.9914e-01],
        [ 3.7161e-01, -8.0064e-01,  6.9206e-01],
        [-1.8670e+00, -2.6849e-01, -7.1033e-01],
        [ 1.6659e+00, -6.6649e-01,  2.5671e+00],
        [-1.3198e+00,  9.6104e-01, -2.0985e-01],
        [ 1.1114e-02, -7.8026e-01,  6.3959e-01],
        [-1.2387e+00,  7.5148e-01, -6.6887e-01],
        [ 6.6547e-01, -7.9385e-01, -3.3627e-01],
        [ 1.8095e+00, -7.3227e-01,  2.7062e+00],
        [ 1.8600e+00, -9.7303e-01,  1.8816e+00],
        [-7.4923e-01, -3.6409e-01, -1.0382e+00],
        [ 1.0820e+00, -3.3543e-01, -8.8521e-01],
        [-1.4542e-02, -3.8154e-01,  1.1719e-01],
        [-3.1665e-01,  1.9115e+00,  4.5618e-01],
        [-1.2514e+00, -7.3511e-01, -7.9838e-01],
        [ 1.5617e+00, -3.4291e-01,  6.1972e-01],
        [-5.6531e-01,  8.6892e-01, -9.0513e-01]

In [6]:
torch.save(model.state_dict(), ("C:/Users/Gabriel/Documents/Python/ANN2.pt"))                
                                

In [30]:
print(data2)

[[0.01783333333333333, 24.988333333333344, 0.050833333333333335], [0.023416666666666665, -32.44333333333335, 0.04166666666666668], [0.02313333333333334, -9.365833333333322, 0.041666666666666664], [0.020691666666666674, 32.817499999999995, 0.034999999999999976], [0.019733333333333325, -26.63583333333334, 0.03500000000000003], [0.015975, 132.69500000000005, 0.02749999999999997], [0.01776666666666667, 242.3891666666666, 0.027500000000000007], [0.012699999999999989, 146.2941666666667, 0.029166666666666674], [0.013891666666666672, 193.01666666666657, 0.01416666666666666], [0.01153333333333332, 129.1691666666667, 0.025000000000000022], [0.009850000000000025, 118.19666666666672, 0.01833333333333335], [0.010924999999999999, 140.48833333333323, 0.00916666666666662]]
