In [1]:
import numpy as np
import xlrd
import pandas as pd
book = xlrd.open_workbook('kinetic data complete.xlsx')
sheet = book.sheet_by_name('Sheet1')
data = [[sheet.cell_value(r, c) for c in range(0,3)] for r in range(0,312)]
data2 = [[sheet.cell_value(r, c) for c in range(3,4)] for r in range(0,312)]
test_data = np.array(data)
light_data = np.array(data2)


[[2.00000000e-01 2.00000000e+02 0.00000000e+00]
 [2.12165809e-01 1.90032245e+02 3.80711351e-02]
 [2.24639139e-01 1.79545784e+02 7.70455388e-02]
 [2.37359202e-01 1.68549087e+02 1.16741806e-01]
 [2.50252051e-01 1.57059217e+02 1.56944517e-01]
 [2.63228480e-01 1.45103961e+02 1.97400008e-01]
 [2.76181294e-01 1.32724569e+02 2.37810842e-01]
 [2.88981686e-01 1.19979264e+02 2.77828367e-01]
 [3.01474294e-01 1.06947878e+02 3.17042366e-01]
 [3.13470497e-01 9.37379185e+01 3.54966746e-01]
 [3.24739443e-01 8.04924758e+01 3.91020134e-01]
 [3.34996717e-01 6.74001281e+01 4.24501063e-01]
 [3.43891945e-01 5.47061026e+01 4.54560775e-01]
 [3.51000624e-01 4.27213968e+01 4.80185777e-01]
 [3.55834754e-01 3.18204667e+01 5.00223622e-01]
 [3.57901858e-01 2.24079335e+01 5.13520020e-01]
 [3.56848092e-01 1.48293885e+01 5.19249239e-01]
 [3.52668966e-01 9.23197481e+00 5.17399532e-01]
 [3.45839612e-01 5.46364071e+00 5.09072266e-01]
 [3.37185910e-01 3.12786215e+00 4.96183142e-01]
 [3.27568647e-01 1.76353700e+00 4.807323

In [4]:
writer1 = pd.ExcelWriter('generateddatakinetic.xlsx', engine='xlsxwriter')
for i in range(1, 26):
    b = np.random.normal(test_data,test_data*0.05*0.333,(312,3))
   
    df = pd.DataFrame(b)
    df2 = pd.DataFrame(light_data)
    startrow = (i-1)*312
    df.to_excel(writer1,startrow=startrow, header=False, index=False)
    df2.to_excel(writer1,startrow=startrow,startcol=3, header=False, index=False)
    c = np.random.normal(test_data,test_data*0.03*0.333,(312,3))
    df = pd.DataFrame(c)
    startrow = (i-1)*312+25*312
    df.to_excel(writer1,startrow=startrow, header=False, index=False)
    df2.to_excel(writer1,startrow=startrow,startcol=3, header=False, index=False)
writer1.save()


In [5]:
book = xlrd.open_workbook('generateddatakineticwithgradient.xlsx')
sheet = book.sheet_by_name('Sheet1')
data3 = [[sheet.cell_value(r, c) for c in range(0,7)] for r in range(0,15600)]
complete_data = np.array(data3)
prepared_data = np.delete(complete_data, list(range(25, complete_data.shape[0], 26)), axis=0)
writer2 = pd.ExcelWriter('prepareddatakinetic.xlsx', engine='xlsxwriter')
df3 = pd.DataFrame(prepared_data)
df3.to_excel(writer2, header=False,index=False)
writer2.save()

In [6]:
book = xlrd.open_workbook('kinetic data complete with gradient.xlsx')
sheet = book.sheet_by_name('Sheet1')
data3 = [[sheet.cell_value(r, c) for c in range(0,7)] for r in range(0,312)]
complete_data = np.array(data3)
prepared_data = np.delete(complete_data, list(range(25, complete_data.shape[0], 26)), axis=0)
writer2 = pd.ExcelWriter('kinetic data for standardisation.xlsx', engine='xlsxwriter')
df3 = pd.DataFrame(prepared_data)
df3.to_excel(writer2, header=False,index=False)
writer2.save()